### ISSUE TITLE
ถ้าต้องการย้าย admin ให้เข้าไปอยู่ใน sub dir แล้วเขียน front ใหม่

### ISSUE THREAD

**Issue by ElonJTrump** [goragod/adminframework#1]
ขอสอบถามวิธีว่าถ้าต้องการย้าย ส่วน admin เข้าไปใน sub directory เช่น /admin เพื่อจะเขียน module front แยก จะทำได้อย่างไร

**Comment by goragodwiriya** [comment]
มีตัวอย่างอยู่ในโปรเจ็ค GCMS ครับ
